adding a second function to decrease even values.
adesautels-steer/process-data-example pull request #1
Opened 2023-03-02 16:46 UTC by AnthonySparling

Just trying the pull request. This will set all even values to 2 but in a roundabout way.

2023-03-02 16:52 UTC, adesautels-steer requested changes
Looks pretty good! Can you please address the one inline comment I made? I'll pull it in after that. Thanks!

2023-03-02 16:52 UTC, adesautels-steer commented on process_data.py
> +def extra_process(x):
Let's give this function a more descriptive name (mostly just showing you how inline comments work).

2023-03-02 18:59 UTC, AnthonySparling commented
Okay, function name has been updated and I had to correct an issue in the function.

2023-03-09 00:42 UTC, merged

2023-03-09 00:43 UTC, adesautels-steer commented
Looks good—just resolved a conflict with Luc's latest commit and pulled it in!